# Generated by Django 4.2.28 on 2026-02-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roshan_ai', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roshan_ai.document'),
        ),
    ]
