# Generated by Django 4.2.28 on 2026-02-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roshan_ai', '0006_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='RoshanDocument',
        ),
    ]
