# Generated by Django 4.2.28 on 2026-02-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roshan_ai', '0007_rename_document_roshandocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='RoshanQuestion',
        ),
    ]
