# Generated by Django 4.2.28 on 2026-02-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roshan_ai', '0008_rename_question_roshanquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='RoshanTag',
        ),
    ]
