# Generated by Django 4.2.28 on 2026-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan_ai', '0009_rename_tag_roshantag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roshanquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
