# Generated by Django 4.2.28 on 2026-02-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan_ai', '0010_alter_roshanquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roshanquestion',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
